CC=mkoctfile 
CFLAGS=-O3 -fno-stack-protector -march=native -mtune=native
INCLUDES=-I"${JAVA_HOME}/include" -I"${JAVA_HOME}/include/linux"

pathPlannerJNI: pathplannerJNI.o transformed_pathplanner.o
	${CC} -v --link-stand-alone ${CFLAGS} ${INCLUDES} -shared -o lib$@.so $^ ${OBJS}

.c.o:
	${CC} ${CFLAGS} ${INCLUDES} -c $<
clean:
	rm -f *.o core *.core *.so 

