TOP=..
.include "$(TOP)/mk/base.mk"

TESTTYPE=interp
TESTS=t00 t01 t02 t03 t04 t05 t06 t07

CASPFILE=arm-swi-small.casp
CASPFILE.t00=arm-swi-small.casp
CASPFILE.t01=arm-swi-small.casp
CASPFILE.t02=arm-swi-small.casp
CASPFILE.t03=arm-swi-small.casp
CASPFILE.t04=arm-swi-small.casp
CASPFILE.t05=arm-swi-small.casp
CASPFILE.t06=arm-swi-small.casp
CASPFILE.t07=arm-swi-small.casp

.include "$(TOP)/mk/testdir.mk"
