TOP=..
include $(TOP)/mk/base.mk

SRCS=\
	common.c mem.c array.c intops.c buffer.c \
	arlib.c genfile.c genfmt.c
LIB=libsupport.a
MYCFLAGS=-I../include -I../include/arch/$(CPU)

include $(TOP)/mk/lib.mk
