#!/usr/bin/env bash

# Start ActiveMQ Broker
bash ./apache-activemq-5.14.0/bin/activemq start

# Wait for ActiveMQ to finish starting
sleep 10

# Start the Evaluation Service
nohup bash evaluation-service.sh > evws.log &
nohup bash grizzly-service.sh > grizzly.log &

bash run
