#!/usr/bin/env bash

# Start ActiveMQ Broker
bash ../../apache-activemq-5.14.0/bin/activemq start

# Wait for ActiveMQ to finish starting
sleep 10

# Start the Evaluation Service
nohup bash evaluation-service.sh > evws.log &
nohup bash grizzly-service.sh > grizzly.log &

runCount=1
mkdir /data/cp3

for test in /data/BambooEvalDir/*
do
	for iteration in "${test}/*"
	do
		for baseline in "${iteration}/*"
		do
			if [[ "${baseline}" =~ .*A ]] || [[ "${baseline}" =~ .*B ]] || [[ "${baseline}" =~ .*ChallengeStage ]]
				then
				/bin/cp -f ${baseline}/inputs/cp3-batteryPerturbations.json ./config/default/
				/bin/cp -f ${baseline}/inputs/cp3-initialParams.json ./config/default/
			fi

			bash run

			mkdir /data/cp3/run-$runCount
			/bin/cp *.log /data/cp3/run-$runCount
			/bin/cp *.json /data/cp3/run-$runCount

			((runCount=$runCount+1))
		done
	done
done
