/* Automatically generated; do not edit */

#ifndef TARGETRELOC_H
#define TARGETRELOC_H
enum reloc_modifier{
   RELOC_MOD_NONE,
   RELOC_MOD_LO,
   RELOC_MOD_HI,
   RELOC_MOD_ULO,
   RELOC_MOD_UHI,
   RELOC_MOD_H44,
   RELOC_MOD_M44,
   RELOC_MOD_L44,
   RELOC_MOD_GOT,
   RELOC_MOD_PLT,
};

enum reloc_field{
   RELOC_FIELD_DISP30,
   RELOC_FIELD_DISP22,
   RELOC_FIELD_DISP19,
   RELOC_FIELD_D16LO,
   RELOC_FIELD_IMM22,
   RELOC_FIELD_SIMM13,
   RELOC_FIELD_SIMM11,
   RELOC_FIELD_SIMM10,
   RELOC_FIELD_IMM7,
   RELOC_FIELD_IMM6,
   RELOC_FIELD_IMM5,
   RELOC_FIELD_DATA64,
   RELOC_FIELD_DATA32,
   RELOC_FIELD_DATA16,
   RELOC_FIELD_DATA8,
};

#define RELOC_FIELD_DEFAULT RELOC_FIELD_DISP30
#endif /* TARGETRELOC_H */
