/* Automatically generated; do not edit */
#include "targetdefs.h"
struct label; /* from label.h */
struct compound_addr_ri;
struct compound_addr_rr;
struct compound_addr_rx;
struct compound_braddr_r_asi;
struct compound_braddr_r_immasi;
struct compound_braddr_ri;
struct compound_braddr_ri_asi;
struct compound_braddr_rr;
struct compound_braddr_rr_immasi;
struct compound_braddr_rx;
struct compound_trapnum_ri;
struct compound_trapnum_rr;
void insn_sethi_u32num_reg(int line, uint32_t val1, uint8_t val2);
void insn_sethi_expr_reg(int line, struct expr * val1, uint8_t val2);
void insn_add_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_add_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_addcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_addcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_addc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_addc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_addccc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_addccc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_sub_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sub_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_subcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_subcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_subc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_subc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_subccc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_subccc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_and_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_and_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_andcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_andcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_andn_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_andn_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_andncc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_andncc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_or_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_or_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_or_reg_expr_reg(int line, uint8_t val1, struct expr * val2, uint8_t val3);
void insn_orcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_orcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_orn_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_orn_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_orncc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_orncc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_xor_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_xor_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_xorcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_xorcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_xnor_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_xnor_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_xnorcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_xnorcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_popc_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_popc_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_save_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_save_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_restore_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_restore_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_taddcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_taddcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_taddcctv_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_taddcctv_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_tsubcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_tsubcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_tsubcctv_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_tsubcctv_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_addx_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_addx_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_addxcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_addxcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_subx_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_subx_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_subxcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_subxcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_sll_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sll_reg_u5num_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_srl_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_srl_reg_u5num_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sra_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sra_reg_u5num_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sllx_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sllx_reg_u6num_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_srlx_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_srlx_reg_u6num_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_srax_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_srax_reg_u6num_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_umul_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_umul_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_smul_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_smul_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_umulcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_umulcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_smulcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_smulcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_mulscc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_mulscc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_sdiv_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sdiv_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_udiv_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_udiv_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_sdivcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sdivcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_udivcc_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_udivcc_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_mulx_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_mulx_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_sdivx_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sdivx_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_udivx_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_udivx_reg_i13num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_fadds_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_faddd_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_faddq_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fsubs_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fsubd_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fsubq_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fcmps_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fcmpd_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fcmpq_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fcmpes_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fcmped_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fcmpeq_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fstox_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fdtox_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fqtox_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fstoi_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fdtoi_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fqtoi_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fxtos_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fxtod_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fxtoq_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fitos_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fitod_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fitoq_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fstod_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fstoq_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fdtos_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fdtoq_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fqtos_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fqtod_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fmovs_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fmovd_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fmovq_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fnegs_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fnegd_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fnegq_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fabss_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fabsd_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fabsq_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fsqrts_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fsqrtd_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fsqrtq_freg_freg(int line, uint8_t val1, uint8_t val2);
void insn_fmuls_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmuld_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmulq_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fsmuld_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fdmulq_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fdivs_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fdivd_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fdivq_freg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_brz_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brz_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brz_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brz_a_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brz_a_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brz_a_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlez_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlez_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlez_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlez_a_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlez_a_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlez_a_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlz_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlz_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlz_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlz_a_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlz_a_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brlz_a_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brnz_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brnz_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brnz_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brnz_a_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brnz_a_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brnz_a_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgz_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgz_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgz_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgz_a_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgz_a_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgz_a_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgez_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgez_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgez_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgez_a_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgez_a_pt_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_brgez_a_pn_reg_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fba_symbol(int line, struct expr * val1);
void insn_fba_a_symbol(int line, struct expr * val1);
void insn_fbn_symbol(int line, struct expr * val1);
void insn_fbn_a_symbol(int line, struct expr * val1);
void insn_fbu_symbol(int line, struct expr * val1);
void insn_fbu_a_symbol(int line, struct expr * val1);
void insn_fbg_symbol(int line, struct expr * val1);
void insn_fbg_a_symbol(int line, struct expr * val1);
void insn_fbug_symbol(int line, struct expr * val1);
void insn_fbug_a_symbol(int line, struct expr * val1);
void insn_fbl_symbol(int line, struct expr * val1);
void insn_fbl_a_symbol(int line, struct expr * val1);
void insn_fbul_symbol(int line, struct expr * val1);
void insn_fbul_a_symbol(int line, struct expr * val1);
void insn_fblg_symbol(int line, struct expr * val1);
void insn_fblg_a_symbol(int line, struct expr * val1);
void insn_fbne_symbol(int line, struct expr * val1);
void insn_fbne_a_symbol(int line, struct expr * val1);
void insn_fbe_symbol(int line, struct expr * val1);
void insn_fbe_a_symbol(int line, struct expr * val1);
void insn_fbue_symbol(int line, struct expr * val1);
void insn_fbue_a_symbol(int line, struct expr * val1);
void insn_fbge_symbol(int line, struct expr * val1);
void insn_fbge_a_symbol(int line, struct expr * val1);
void insn_fbuge_symbol(int line, struct expr * val1);
void insn_fbuge_a_symbol(int line, struct expr * val1);
void insn_fble_symbol(int line, struct expr * val1);
void insn_fble_a_symbol(int line, struct expr * val1);
void insn_fbule_symbol(int line, struct expr * val1);
void insn_fbule_a_symbol(int line, struct expr * val1);
void insn_fbo_symbol(int line, struct expr * val1);
void insn_fbo_a_symbol(int line, struct expr * val1);
void insn_fbnz_symbol(int line, struct expr * val1);
void insn_fbnz_a_symbol(int line, struct expr * val1);
void insn_fbz_symbol(int line, struct expr * val1);
void insn_fbz_a_symbol(int line, struct expr * val1);
void insn_fba_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fba_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fba_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fba_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fba_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fba_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbn_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbn_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbn_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbn_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbn_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbu_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbu_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbu_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbu_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbu_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbu_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbg_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbg_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbg_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbg_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbg_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbg_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbug_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbug_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbug_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbug_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbug_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbug_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbl_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbl_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbl_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbl_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbl_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbl_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbul_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbul_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbul_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbul_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbul_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbul_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fblg_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fblg_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fblg_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fblg_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fblg_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fblg_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbne_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbne_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbne_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbne_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbne_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbne_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbe_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbe_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbe_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbe_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbe_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbe_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbue_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbue_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbue_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbue_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbue_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbue_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbge_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbge_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbge_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbge_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbge_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbge_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbuge_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbuge_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbuge_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbuge_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbuge_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbuge_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fble_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fble_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fble_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fble_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fble_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fble_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbule_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbule_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbule_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbule_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbule_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbule_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbo_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbo_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbo_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbo_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbo_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbo_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbnz_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbnz_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbnz_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbnz_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbnz_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbnz_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbz_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbz_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbz_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbz_a_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbz_a_pt_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fbz_a_pn_fcc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ba_symbol(int line, struct expr * val1);
void insn_ba_a_symbol(int line, struct expr * val1);
void insn_bn_symbol(int line, struct expr * val1);
void insn_bn_a_symbol(int line, struct expr * val1);
void insn_bne_symbol(int line, struct expr * val1);
void insn_bne_a_symbol(int line, struct expr * val1);
void insn_be_symbol(int line, struct expr * val1);
void insn_be_a_symbol(int line, struct expr * val1);
void insn_bg_symbol(int line, struct expr * val1);
void insn_bg_a_symbol(int line, struct expr * val1);
void insn_ble_symbol(int line, struct expr * val1);
void insn_ble_a_symbol(int line, struct expr * val1);
void insn_bge_symbol(int line, struct expr * val1);
void insn_bge_a_symbol(int line, struct expr * val1);
void insn_bl_symbol(int line, struct expr * val1);
void insn_bl_a_symbol(int line, struct expr * val1);
void insn_bgu_symbol(int line, struct expr * val1);
void insn_bgu_a_symbol(int line, struct expr * val1);
void insn_bleu_symbol(int line, struct expr * val1);
void insn_bleu_a_symbol(int line, struct expr * val1);
void insn_bcc_symbol(int line, struct expr * val1);
void insn_bcc_a_symbol(int line, struct expr * val1);
void insn_bcs_symbol(int line, struct expr * val1);
void insn_bcs_a_symbol(int line, struct expr * val1);
void insn_bpos_symbol(int line, struct expr * val1);
void insn_bpos_a_symbol(int line, struct expr * val1);
void insn_bneg_symbol(int line, struct expr * val1);
void insn_bneg_a_symbol(int line, struct expr * val1);
void insn_bvc_symbol(int line, struct expr * val1);
void insn_bvc_a_symbol(int line, struct expr * val1);
void insn_bvs_symbol(int line, struct expr * val1);
void insn_bvs_a_symbol(int line, struct expr * val1);
void insn_bnz_symbol(int line, struct expr * val1);
void insn_bnz_a_symbol(int line, struct expr * val1);
void insn_bz_symbol(int line, struct expr * val1);
void insn_bz_a_symbol(int line, struct expr * val1);
void insn_bgeu_symbol(int line, struct expr * val1);
void insn_bgeu_a_symbol(int line, struct expr * val1);
void insn_blu_symbol(int line, struct expr * val1);
void insn_blu_a_symbol(int line, struct expr * val1);
void insn_ba_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ba_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ba_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ba_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ba_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ba_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bn_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bn_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bn_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bn_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bn_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bne_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bne_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bne_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bne_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bne_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bne_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_be_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_be_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_be_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_be_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_be_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_be_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bg_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bg_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bg_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bg_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bg_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bg_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ble_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ble_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ble_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ble_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ble_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_ble_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bge_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bge_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bge_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bge_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bge_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bge_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bl_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bl_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bl_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bl_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bl_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bl_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgu_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgu_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgu_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgu_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgu_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgu_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bleu_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bleu_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bleu_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bleu_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bleu_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bleu_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcc_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcc_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcc_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcc_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcc_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcc_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcs_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcs_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcs_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcs_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcs_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bcs_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bpos_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bpos_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bpos_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bpos_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bpos_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bpos_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bneg_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bneg_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bneg_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bneg_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bneg_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bneg_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvc_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvc_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvc_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvc_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvc_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvc_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvs_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvs_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvs_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvs_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvs_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bvs_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bnz_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bnz_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bnz_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bnz_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bnz_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bnz_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bz_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bz_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bz_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bz_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bz_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bz_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgeu_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgeu_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgeu_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgeu_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgeu_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_bgeu_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_blu_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_blu_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_blu_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_blu_a_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_blu_a_pt_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_blu_a_pn_icc_symbol(int line, uint8_t val1, struct expr * val2);
void insn_fmovsa_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovda_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqa_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsn_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdn_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqn_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsne_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdne_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqne_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovse_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovde_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqe_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsg_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdg_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqg_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsle_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdle_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqle_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsge_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdge_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqge_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsl_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdl_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovql_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsgu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdgu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqgu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsleu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdleu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqleu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovscc_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdcc_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqcc_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovscs_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdcs_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqcs_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovspos_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdpos_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqpos_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsneg_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdneg_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqneg_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsvc_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdvc_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqvc_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsvs_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdvs_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqvs_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsnz_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdnz_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqnz_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsz_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdz_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqz_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsgeu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdgeu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqgeu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovslu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdlu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqlu_icc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsa_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovda_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqa_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsn_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdn_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqn_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsu_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdu_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqu_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsg_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdg_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqg_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsug_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdug_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqug_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsl_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdl_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovql_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsul_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdul_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqul_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovslg_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdlg_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqlg_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsne_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdne_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqne_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovse_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovde_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqe_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsue_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdue_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovque_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsge_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdge_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqge_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsuge_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovduge_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovquge_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsle_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdle_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqle_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsule_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdule_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqule_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovso_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdo_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqo_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsnz_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdnz_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqnz_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovsz_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovdz_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovqz_fcc_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrsz_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrdz_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrqz_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrslez_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrdlez_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrqlez_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrslz_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrdlz_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrqlz_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrsnz_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrdnz_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrqnz_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrsg_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrdg_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrqg_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrsgez_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrdgez_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrqgez_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrse_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrde_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrqe_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrsne_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrdne_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_fmovrqne_reg_freg_freg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_mova_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_mova_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movn_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movn_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movne_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movne_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_move_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_move_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movg_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movg_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movle_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movle_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movge_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movge_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movl_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movl_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movgu_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movgu_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movleu_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movleu_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movcc_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movcc_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movcs_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movcs_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movpos_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movpos_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movneg_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movneg_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movvc_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movvc_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movvs_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movvs_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movnz_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movnz_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movz_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movz_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movgeu_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movgeu_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movlu_icc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movlu_icc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_mova_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_mova_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movn_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movn_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movu_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movu_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movg_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movg_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movug_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movug_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movl_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movl_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movul_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movul_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movlg_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movlg_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movne_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movne_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_move_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_move_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movue_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movue_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movge_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movge_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movuge_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movuge_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movle_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movle_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movule_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movule_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movo_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movo_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movnz_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movnz_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movz_fcc_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movz_fcc_i11num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movrz_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movrz_reg_i10num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movrlez_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movrlez_reg_i10num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movrlz_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movrlz_reg_i10num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movrnz_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movrnz_reg_i10num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movrgz_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movrgz_reg_i10num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movrgez_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movrgez_reg_i10num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movre_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movre_reg_i10num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_movrne_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_movrne_reg_i10num_reg(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_membar_membarmask(int line, uint8_t val1);
void insn_stbar_(int line);
void insn_flush_addr_rr(int line, struct compound_addr_rr * val1);
void insn_flush_addr_ri(int line, struct compound_addr_ri * val1);
void insn_prefetch_braddr_rr_u5num(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_prefetch_braddr_ri_u5num(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_prefetcha_braddr_rr_immasi_u5num(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_prefetcha_braddr_ri_asi_u5num(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_casa_braddr_r_immasi_reg_reg(int line, struct compound_braddr_r_immasi * val1, uint8_t val2, uint8_t val3);
void insn_casa_braddr_r_asi_reg_reg(int line, struct compound_braddr_r_asi * val1, uint8_t val2, uint8_t val3);
void insn_casxa_braddr_r_immasi_reg_reg(int line, struct compound_braddr_r_immasi * val1, uint8_t val2, uint8_t val3);
void insn_casxa_braddr_r_asi_reg_reg(int line, struct compound_braddr_r_asi * val1, uint8_t val2, uint8_t val3);
void insn_ldstub_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldstub_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldstub_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldstuba_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_ldstuba_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_swap_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_swap_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_swapa_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_swapa_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_ld_braddr_rr_freg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ld_braddr_ri_freg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ld_braddr_rx_freg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldd_braddr_rr_freg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldd_braddr_ri_freg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldd_braddr_rx_freg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldq_braddr_rr_freg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldq_braddr_ri_freg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldq_braddr_rx_freg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ld_braddr_rr_fsr(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ld_braddr_ri_fsr(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ld_braddr_rx_fsr(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldx_braddr_rr_fsr(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldx_braddr_ri_fsr(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldx_braddr_rx_fsr(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_lda_braddr_rr_immasi_freg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_lda_braddr_ri_asi_freg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_ldda_braddr_rr_immasi_freg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_ldda_braddr_ri_asi_freg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_ldqa_braddr_rr_immasi_freg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_ldqa_braddr_ri_asi_freg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_ldsb_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldsb_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldsb_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldsh_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldsh_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldsh_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldsw_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldsw_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldsw_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldub_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldub_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldub_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_lduh_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_lduh_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_lduh_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_lduw_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_lduw_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_lduw_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldx_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldx_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldx_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldd_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldd_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldd_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ld_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ld_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ld_braddr_rx_reg(int line, struct compound_braddr_rx * val1, uint8_t val2);
void insn_ldsba_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_ldsba_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_ldsha_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_ldsha_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_ldswa_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_ldswa_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_lduba_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_lduba_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_lduha_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_lduha_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_lduwa_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_lduwa_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_ldxa_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_ldxa_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_ldda_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_ldda_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_lda_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_lda_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_st_freg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_st_freg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_st_freg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_std_freg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_std_freg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_std_freg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stq_freg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stq_freg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stq_freg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_st_fsr_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_st_fsr_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_st_fsr_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stx_fsr_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stx_fsr_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stx_fsr_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_sta_freg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_sta_freg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stda_freg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stda_freg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stqa_freg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stqa_freg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stb_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stb_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stb_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_sth_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_sth_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_sth_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stw_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stw_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stw_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stx_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stx_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stx_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_std_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_std_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_std_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stsb_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stsb_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stsb_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stub_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stub_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stub_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stsh_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stsh_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stsh_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stuh_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stuh_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stuh_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_st_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_st_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_st_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stsw_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stsw_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stsw_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stuw_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stuw_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stuw_reg_braddr_rx(int line, uint8_t val1, struct compound_braddr_rx * val2);
void insn_stba_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stba_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stha_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stha_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stwa_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stwa_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stxa_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stxa_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stda_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stda_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stsba_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stsba_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stuba_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stuba_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stsha_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stsha_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stuha_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stuha_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stswa_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stswa_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_stuwa_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stuwa_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_sta_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_sta_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_call_symbol(int line, struct expr * val1);
void insn_call_symbol_number(int line, struct expr * val1, uint32_t val2);
void insn_jmpl_addr_rr_reg(int line, struct compound_addr_rr * val1, uint8_t val2);
void insn_jmpl_addr_ri_reg(int line, struct compound_addr_ri * val1, uint8_t val2);
void insn_return_addr_rr(int line, struct compound_addr_rr * val1);
void insn_return_addr_ri(int line, struct compound_addr_ri * val1);
void insn_illtrap_u22num(int line, uint32_t val1);
void insn_sir_i13num(int line, int16_t val1);
void insn_ta_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_ta_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tn_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tn_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tne_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tne_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_te_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_te_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tg_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tg_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tle_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tle_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tge_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tge_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tl_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tl_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tgu_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tgu_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tleu_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tleu_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tcc_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tcc_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tcs_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tcs_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tpos_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tpos_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tneg_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tneg_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tvc_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tvc_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tvs_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tvs_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tnz_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tnz_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tz_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tz_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tgeu_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tgeu_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_tlu_icc_trapnum_rr(int line, uint8_t val1, struct compound_trapnum_rr * val2);
void insn_tlu_icc_trapnum_ri(int line, uint8_t val1, struct compound_trapnum_ri * val2);
void insn_nop_(int line);
void insn_rd_asr_reg(int line, uint8_t val1, uint8_t val2);
void insn_wr_reg_reg_asr(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_wr_reg_i13num_asr(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_impl1_u5num_u19num(int line, uint8_t val1, uint32_t val2);
void insn_impl2_u5num_u19num(int line, uint8_t val1, uint32_t val2);
void insn_rdpr_pr_reg(int line, uint8_t val1, uint8_t val2);
void insn_wrpr_reg_reg_pr(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_wrpr_reg_i13num_pr(int line, uint8_t val1, int16_t val2, uint8_t val3);
void insn_done_(int line);
void insn_retry_(int line);
void insn_flushw_(int line);
void insn_saved_(int line);
void insn_restored_(int line);
void insn_cmp_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_cmp_reg_i13num(int line, uint8_t val1, int16_t val2);
void insn_jmp_addr_rr(int line, struct compound_addr_rr * val1);
void insn_jmp_addr_ri(int line, struct compound_addr_ri * val1);
void insn_call_addr_rr(int line, struct compound_addr_rr * val1);
void insn_call_addr_ri(int line, struct compound_addr_ri * val1);
void insn_call_addr_rr_number(int line, struct compound_addr_rr * val1, uint32_t val2);
void insn_call_addr_ri_number(int line, struct compound_addr_ri * val1, uint32_t val2);
void insn_ret_(int line);
void insn_retl_(int line);
void insn_save_(int line);
void insn_restore_(int line);
void insn_iprefetch_symbol(int line, struct expr * val1);
void insn_tst_reg(int line, uint8_t val1);
void insn_setuw_u32num_reg(int line, uint32_t val1, uint8_t val2);
void insn_set_u32num_reg(int line, uint32_t val1, uint8_t val2);
void insn_setsw_i32num_reg(int line, int32_t val1, uint8_t val2);
void insn_setx_i64num_reg_reg(int line, int64_t val1, uint8_t val2, uint8_t val3);
void insn_signx_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_signx_reg(int line, uint8_t val1);
void insn_not_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_not_reg(int line, uint8_t val1);
void insn_neg_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_neg_reg(int line, uint8_t val1);
void insn_cas_braddr_r_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_casl_braddr_r_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_casx_braddr_r_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_casxl_braddr_r_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_inc_reg(int line, uint8_t val1);
void insn_inc_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_inccc_reg(int line, uint8_t val1);
void insn_inccc_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_dec_reg(int line, uint8_t val1);
void insn_dec_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_deccc_reg(int line, uint8_t val1);
void insn_deccc_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_btst_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_btst_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_bset_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_bset_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_bclr_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_bclr_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_btog_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_btog_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_clr_reg(int line, uint8_t val1);
void insn_clrb_braddr_rr(int line, struct compound_braddr_rr * val1);
void insn_clrb_braddr_ri(int line, struct compound_braddr_ri * val1);
void insn_clrh_braddr_rr(int line, struct compound_braddr_rr * val1);
void insn_clrh_braddr_ri(int line, struct compound_braddr_ri * val1);
void insn_clr_braddr_rr(int line, struct compound_braddr_rr * val1);
void insn_clr_braddr_ri(int line, struct compound_braddr_ri * val1);
void insn_clrx_braddr_rr(int line, struct compound_braddr_rr * val1);
void insn_clrx_braddr_ri(int line, struct compound_braddr_ri * val1);
void insn_clruw_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_clruw_reg(int line, uint8_t val1);
void insn_mov_reg_reg(int line, uint8_t val1, uint8_t val2);
void insn_mov_i13num_reg(int line, int16_t val1, uint8_t val2);
void insn_mov_asr_reg(int line, uint8_t val1, uint8_t val2);
void insn_mov_reg_asr(int line, uint8_t val1, uint8_t val2);
void insn_ldn_braddr_rr_reg(int line, struct compound_braddr_rr * val1, uint8_t val2);
void insn_ldn_braddr_ri_reg(int line, struct compound_braddr_ri * val1, uint8_t val2);
void insn_ldna_braddr_rr_immasi_reg(int line, struct compound_braddr_rr_immasi * val1, uint8_t val2);
void insn_ldna_braddr_ri_asi_reg(int line, struct compound_braddr_ri_asi * val1, uint8_t val2);
void insn_stn_reg_braddr_rr(int line, uint8_t val1, struct compound_braddr_rr * val2);
void insn_stn_reg_braddr_ri(int line, uint8_t val1, struct compound_braddr_ri * val2);
void insn_stna_reg_braddr_rr_immasi(int line, uint8_t val1, struct compound_braddr_rr_immasi * val2);
void insn_stna_reg_braddr_ri_asi(int line, uint8_t val1, struct compound_braddr_ri_asi * val2);
void insn_slln_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_slln_reg_u6num_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_srln_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_srln_reg_u6num_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sran_reg_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_sran_reg_u6num_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_casn_braddr_r_reg_reg(int line, uint8_t val1, uint8_t val2, uint8_t val3);
void insn_casna_braddr_r_immasi_reg_reg(int line, struct compound_braddr_r_immasi * val1, uint8_t val2, uint8_t val3);
void insn_casna_braddr_r_asi_reg_reg(int line, struct compound_braddr_r_asi * val1, uint8_t val2, uint8_t val3);
void insn_clrn_braddr_rr(int line, struct compound_braddr_rr * val1);
void insn_clrn_braddr_ri(int line, struct compound_braddr_ri * val1);
void directive_register_r_rtag(int line, uint8_t val1, uint8_t val2);
void directive_set_s(int line, struct expr * val1);
void directive_unset_s(int line, struct expr * val1);
void directive_set_s_x(int line, struct expr * val1, struct expr * val2);
void directive_file_q(int line, const char * val1);
void directive_file_x(int line, struct expr * val1);
void directive_ident_q(int line, const char * val1);
void directive_gnu_attribute_n_n(int line, uint32_t val1, uint32_t val2);
void directive_text_(int line);
void directive_rdata_(int line);
void directive_data_(int line);
void directive_bss_(int line);
void directive_section_s(int line, struct expr * val1);
void directive_section_s_q(int line, struct expr * val1, const char * val2);
void directive_section_s_q_q(int line, struct expr * val1, const char * val2, const char * val3);
void directive_section_s_q_q_x(int line, struct expr * val1, const char * val2, const char * val3, struct expr * val4);
void directive_section_s_q_q_x_x(int line, struct expr * val1, const char * val2, const char * val3, struct expr * val4, struct expr * val5);
void directive_section_s_q_secty(int line, struct expr * val1, const char * val2, const char * val3);
void directive_section_s_q_secty_x(int line, struct expr * val1, const char * val2, const char * val3, struct expr * val4);
void directive_section_s_q_secty_x_x(int line, struct expr * val1, const char * val2, const char * val3, struct expr * val4, struct expr * val5);
void directive_section_q(int line, const char * val1);
void directive_previous_(int line);
void directive_align_mz(int line, uint32_t val1);
void directive_align_n(int line, uint32_t val1);
void directive_space_n(int line, uint32_t val1);
void directive_lcomm_s_n(int line, struct expr * val1, uint32_t val2);
void directive_lcomm_s_n_n(int line, struct expr * val1, uint32_t val2, uint32_t val3);
void directive_comm_s_n(int line, struct expr * val1, uint32_t val2);
void directive_comm_s_n_n(int line, struct expr * val1, uint32_t val2, uint32_t val3);
void directive_local_s(int line, struct expr * val1);
void directive_globl_s(int line, struct expr * val1);
void directive_global_s(int line, struct expr * val1);
void directive_extern_s(int line, struct expr * val1);
void directive_type_s_symty(int line, struct expr * val1, const char * val2);
void directive_ent_s(int line, struct expr * val1);
void directive_end_s(int line, struct expr * val1);
void directive_size_s_x(int line, struct expr * val1, struct expr * val2);
void directive_frame_r_n_r(int line, uint8_t val1, uint32_t val2, uint8_t val3);
void directive_mask_n_n(int line, uint32_t val1, uint32_t val2);
void directive_fmask_n_n(int line, uint32_t val1, uint32_t val2);
void directive_ascii_q(int line, const char * val1);
void directive_asciz_q(int line, const char * val1);
void directive_8byte_x(int line, struct expr * val1);
void directive_word_x(int line, struct expr * val1);
void directive_4byte_x(int line, struct expr * val1);
void directive_hword_x(int line, struct expr * val1);
void directive_half_x(int line, struct expr * val1);
void directive_short_x(int line, struct expr * val1);
void directive_2byte_x(int line, struct expr * val1);
void directive_byte_x(int line, struct expr * val1);
void directive_int_x(int line, struct expr * val1);
void directive_long_x(int line, struct expr * val1);
void directive_cfi_startproc_(int line);
void directive_cfi_endproc_(int line);
void directive_cfi_signal_frame_(int line);
void directive_cfi_def_cfa_r_n(int line, uint8_t val1, uint32_t val2);
void directive_cfi_def_cfa_n_n(int line, uint32_t val1, uint32_t val2);
void directive_cfi_offset_r_n(int line, uint8_t val1, uint32_t val2);
void directive_cfi_offset_n_n(int line, uint32_t val1, uint32_t val2);
void directive_cfi_return_column_r(int line, uint8_t val1);
void directive_cfi_window_save_(int line);
void directive_cfi_register_n_n(int line, uint32_t val1, uint32_t val2);
void directive_cfi_def_cfa_register_n(int line, uint32_t val1);
void directive_common_s_n_q(int line, struct expr * val1, uint32_t val2, const char * val3);
void directive_reserve_s_n_q(int line, struct expr * val1, uint32_t val2, const char * val3);
void directive_common_s_n_n(int line, struct expr * val1, uint32_t val2, uint32_t val3);
void directive_reserve_s_n_n(int line, struct expr * val1, uint32_t val2, uint32_t val3);
void directive_nword_x(int line, struct expr * val1);
void directive_proc_(int line);
void directive_proc_x(int line, struct expr * val1);
void directive_seg_q(int line, const char * val1);
void directive_skip_n(int line, uint32_t val1);
void directive_xword_x(int line, struct expr * val1);
void directive_section_x_q_secty(int line, struct expr * val1, const char * val2, const char * val3);
void directive_syntax_s(int line, struct expr * val1);
void directive_arch_s(int line, struct expr * val1);
void directive_arch_extension_s(int line, struct expr * val1);
void directive_cpu_s(int line, struct expr * val1);
void directive_cpu_x(int line, struct expr * val1);
void directive_fpu_s(int line, struct expr * val1);
void directive_arm_(int line);
void directive_thumb_(int line);
void directive_code_n(int line, uint32_t val1);
void directive_force_thumb_(int line);
void directive_thumb_func_(int line);
void directive_thumb_set_(int line);
void directive_eabi_attribute_n_n(int line, uint32_t val1, uint32_t val2);
void directive_personality_s(int line, struct expr * val1);
void directive_personalityindex_n(int line, uint32_t val1);
void directive_inst_x(int line, struct expr * val1);
void directive_even_(int line);
void directive_fnstart_(int line);
void directive_fnend_(int line);
