GENTOP=..
include $(GENTOP)/mk/genbase.mk

# commonparser $(WAIT) 
SUBDIRS=\
	genmisc genmodes \
	genlangdefs genlanguage opmatch \
	genencoding genhazmachine genrelocs

include $(GENTOP)/mk/gensubdir.mk
