/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef TestJNI_MAX_PLAN_PTS
#define TestJNI_MAX_PLAN_PTS 128L
#undef TestJNI_END_MARKER
#define TestJNI_END_MARKER 1.7976931348623157E308
#undef TestJNI_DBL_MAX
#define TestJNI_DBL_MAX 1.7976931348623157E308
/*
 * Class:     TestJNI
 * Method:    nativeCreatePlan
 * Signature: (DDDDDDDDDDDDDDDDDDDDDDDDDDD[Ljava/lang/Object;IDD)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_TestJNI_nativeCreatePlan
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jobjectArray, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
